{
 "title": "Monitor",
 "description": "Docker Monitoring Template",
 "tags": [
  "docker",
  "prometheus, ",
  "node-exporter",
  "cadvisor"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_host_name,hostname)"
    }
   },
   {
    "name": "gindex",
    "label": "GPU Index",
    "query": {
     "query": "label_values(nvidia_smi_index, index)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Host Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode='system'} * on(instance) group_left(nodename, hostname) node_host_name{hostname=~\"$node\"}) by (hostname)",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes * on(instance) group_left(nodename, hostname) node_host_name{hostname=~\"$node\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Root Filesystem usage",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"} * on(instance) group_left(nodename, hostname) node_host_name{hostname=~\"$node\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(ALERTS)" }
   ]
  },
  {
   "title": "Targets Online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 6 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (instance)) * 100 * on(instance) group_left(nodename, hostname) node_host_name{hostname=~\"$node\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes) - (node_memory_MemFree_bytes +node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / (node_memory_MemTotal_bytes) * 100 * on(instance) group_left(nodename, hostname) node_host_name{hostname=~\"$node\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Root Filesystem usage",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1 - node_filesystem_avail_bytes {mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) by (instance) * 100 * on(instance) group_left(nodename, hostname) node_host_name{hostname=~\"$node\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Grafana Alerts",
   "type": "alertlist",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GPU info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Name",
   "type": "stat",
   "gridPos": { "h": 31, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(nvidia_smi_gpu_info{index=~\"$gindex\"} * on (instance) group_left(hostname) node_host_name{hostname=~\"$node\"}, \"short_name\", \"$1\", \"name\", \"(?:NVIDIA )?(?:GeForce )?(.*$)\")",
     "legendFormat": "{{hostname}}[{{index}}]: {{short_name}}"
    }
   ]
  },
  {
   "title": "Power Limit",
   "type": "stat",
   "gridPos": { "h": 31, "w": 4, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_power_limit{index=~\"$gindex\"} * on (instance) group_left(hostname) node_host_name{hostname=~\"$node\"}",
     "legendFormat": "{{hostname}} GPU{{index}}"
    }
   ]
  },
  {
   "title": "Current Power Percentage",
   "type": "stat",
   "gridPos": { "h": 31, "w": 3, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nvidia_smi_power_draw{index=~\"$gindex\"} / nvidia_smi_power_limit{index=~\"$gindex\"}) * on (instance) group_left(hostname) node_host_name{hostname=~\"$node\"}",
     "legendFormat": "{{hostname}} GPU{{index}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 31, "w": 3, "x": 11, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{index=~\"$gindex\"} * on (instance) group_left(hostname) node_host_name{hostname=~\"$node\"}",
     "legendFormat": "{{hostname}} GPU{{index}}"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "stat",
   "gridPos": { "h": 31, "w": 4, "x": 14, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_fan_speed{index=~\"$gindex\"} * on (instance) group_left(hostname) node_host_name{hostname=~\"$node\"}",
     "legendFormat": "{{hostname}} GPU{{index}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 31, "w": 4, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nvidia_smi_memory_used{index=~\"$gindex\"} / nvidia_smi_memory_total{index=~\"$gindex\"}) * on (instance) group_left(hostname) node_host_name{hostname=~\"$node\"}",
     "legendFormat": "{{hostname}} GPU{{index}}"
    }
   ]
  },
  {
   "title": "GPU used",
   "type": "stat",
   "gridPos": { "h": 31, "w": 2, "x": 22, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(nvidia_smi_utilization_gpu{index=~\"$gindex\"}[$interval]) * on (instance) group_left(hostname) node_host_name{hostname=~\"$node\"}) by (hostname, index)",
     "legendFormat": "{{hostname}} GPU{{index}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(nvidia_smi_utilization_gpu{index=~\"$gindex\"}[$interval]) * on (instance) group_left(hostname) node_host_name{hostname=~\"$node\"}) by (hostname, index)",
     "legendFormat": "{{hostname}} GPU{{index}}"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(nvidia_smi_utilization_memory{index=~\"$gindex\"}[$interval]) * on (instance) group_left(hostname) node_host_name{hostname=~\"$node\"}) by (hostname, index)",
     "legendFormat": "{{hostname}} GPU{{index}}"
    }
   ]
  },
  { "title": "MooseFS Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Recent Disk Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mfs_disk_error > scalar((time() - (sum_over_time(up{instance=~\"localhost.*\"}[$interval])) * 5))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chunkserver Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mfs_chunkserver_used_bytes / mfs_chunkserver_total_bytes * on(id) group_left(ip) mfs_chunkserver_info",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Missing Chunks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 18, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mfs_class_missing_chunks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Endangered Chunks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mfs_class_endangered_chunks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Undergoal Chunks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mfs_class_undergoal_chunks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 26, "w": 3, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((node_filesystem_size_bytes {job=\"node-exporter\", instance=~\".*9100\", device=~\"/dev/.*\", mountpoint!~\"/var/.*|/tmp/.*\", fstype=\"ext4\"} * on(instance) group_left nvidia_smi_on) > 0) * on(instance) group_left(nodename, hostname) node_host_name{hostname=~\"$node\"}) by (hostname, mountpoint)",
     "legendFormat": "{{hostname}} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Filesystem Available",
   "type": "bargauge",
   "gridPos": { "h": 26, "w": 5, "x": 3, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes / ((node_filesystem_size_bytes {job=\"node-exporter\", instance=~\".*9100\", device=~\"/dev/.*\", mountpoint!~\"/var/.*|/tmp/.*\", fstype=\"ext4\"} * on(instance) group_left nvidia_smi_on) > 0) * on(instance) group_left(nodename, hostname) node_host_name{hostname=~\"$node\"}) by (hostname, mountpoint)",
     "legendFormat": "{{ hostname }} {{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "stat",
   "gridPos": { "h": 26, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(clamp(node_filesystem_size_bytes{device=~\"/dev/.*\", mountpoint!~\"/var/lib/docker/aufs|/tmp/.*\", fstype=\"ext4\"}, 1, 1), 'devicepath', '$1', 'device', '(.*)') * on (devicepath, instance) group_left(hostname) (label_replace(rate(node_disk_read_bytes_total[$interval]), 'devicepath', '/dev/$1', 'device', '(.*)') * on(instance) group_left(nodename, hostname) node_host_name{hostname=~\"$node\"})",
     "legendFormat": "{{ hostname }} {{ mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Write Bytes",
   "type": "stat",
   "gridPos": { "h": 26, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(clamp(node_filesystem_size_bytes{device=~\"/dev/.*\", mountpoint!~\"/var/lib/docker/aufs|/tmp/.*\", fstype=\"ext4\"}, 1, 1), 'devicepath', '$1', 'device', '(.*)') * on (devicepath, instance) group_left(hostname) (label_replace(rate(node_disk_written_bytes_total[$interval]), 'devicepath', '/dev/$1', 'device', '(.*)') * on(instance) group_left(nodename, hostname) node_host_name{hostname=~\"$node\"})",
     "legendFormat": "{{ hostname }} {{ mountpoint}}"
    }
   ]
  },
  {
   "title": "Container Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Node Network Traffic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 21, "x": 0, "y": 143 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
       "legendFormat": "RECEIVE"
      },
      {
       "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
       "legendFormat": "TRANSMIT"
      }
     ]
    },
    {
     "title": "Running Containers",
     "type": "stat",
     "gridPos": { "h": 9, "w": 3, "x": 21, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(rate(container_last_seen{job=\"cadvisor\", name!=\"\"}[5m]))"
      }
     ]
    },
    {
     "title": "Container CPU usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 152 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) by (id,name)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Container Memory Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 152 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_max_usage_bytes{image!=\"\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Running Versions",
     "type": "table-old",
     "gridPos": { "h": 10, "w": 10, "x": 12, "y": 152 },
     "targets": [
      {
       "expr": "cadvisor_version_info",
       "legendFormat": "cAdvisor  Version: {{cadvisorVersion}}"
      },
      {
       "expr": "prometheus_build_info",
       "legendFormat": "Prometheus Version: {{version}}"
      },
      {
       "expr": "node_exporter_build_info",
       "legendFormat": "Node-Exporter Version: {{version}}"
      }
     ]
    },
    {
     "title": "Container Network Input",
     "type": "graph",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 162 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{image!=\"\"}[1m] ) ))",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Container Network Output",
     "type": "graph",
     "gridPos": { "h": 14, "w": 6, "x": 6, "y": 162 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\"}[1m] ) ))",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  }
 ]
}